### ISSUE TITLE
Stardust Dragon Staff Bug

### ISSUE THREAD

**Issue by tanpro260196** [deadsurgeon42/SummonLimit#2]
Bug with Stardust Dragon. Seem like this plugin cannot count how many Stardust Dragon fragments was summoned. It kick users out of the game if they summon more than 4-5 Stardust Dragon.
Please fix it.

**Comment by aylinni-empyrea** [comment]
Please notify me if https://github.com/deadsurgeon42/SummonLimit/commit/ba299425e4b3b8bac1c5049f326464b291218476 has fixed it.

**Comment by aylinni-empyrea** [comment]
Guessing it's fixed so closed.
