### ISSUE TITLE
False positive when using Spider Staff

### ISSUE THREAD

**Issue by sgkoishi** [deadsurgeon42/SummonLimit#4]
According to [wiki](https://terraria.gamepedia.com/Spider_Staff#Notes) and actual test, player can own more than 11 minions(spiders).
This picture shows 13, and maximun is 14.
![](https://cdn.discordapp.com/attachments/304121696657473536/361387435864752152/QQ20170924124313.png "")

**Comment by aylinni-empyrea** [comment]
Can you test if the latest release fixes it?

**Comment by aylinni-empyrea** [comment]
_(I guess that's a yes)_
